production:
    :maximum_size: 100
    :primary_store: 'local'
    :secondary_store: ''
    :stores:
        :tmp:
            :data_folder: './tmp/uploads/'
            :thumbnail_folder: './tmp/uploads/'
        :local:
            :data_folder: './uploads'
            :thumbnail_folder: './uploads'
